version: '3.0'

networks:
  shared-network:
      driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3.7.18-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_URL: amqp://guest:guest@localhost:5672/test
      node: rabbitmq
      restart: always
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      -  shared-network